AWSTemplateFormatVersion: 2010-09-09
Description: |
  
Parameters:
  
Resources: 
LogicalID:
  Type: AWS::EC2::Instance
  Properties:
    ImageId: ami-0a8b4cd432b1c3063
    InstanceType: t2.micro
    KeyName: firstkey
    SecurityGroups:
      -cfn-sec-group
    Tags:
      Tags
  
Outputs: